### ISSUE TITLE
Suggestion: UI

### ISSUE THREAD

**Issue by wouter-heerwegh** [yamashi/NecroUI#2]
Would it be possible to link some labels and stuff to the ui, so thet is just looks a bit more fancy? for instance maybe an experience bar etc. Or a listbox with all the pokemon that you caught with cp and IV or something. All the strings are allready in the necrobot, because they are linked to the top of the cmd window or to the output of the cmd.

**Comment by adriendomoison** [comment]
Hi
I worked on that but it need to be separated from the core https://github.com/NecronomiconCoding/NecroBot/pull/1283
Would somebody be interested in doing it for this project?
![pokemap2](https://cloud.githubusercontent.com/assets/9092210/17227876/5eb2e912-54c5-11e6-9766-887bc9ed2ba8.PNG)
